// import type { ReactElement } from 'react';
import './globals.css';
import type { ReactNode } from 'react';
import { Provider } from './provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};



export default async function RootLayout({ 
    params,
    children,
  }: {
    params: Promise<{ locale: string }>;
    children: ReactNode;
  }) {
    
  const { locale } = await params;
    
  return (
    <html lang="en" dir={locale === 'en' ? 'ltr' : 'rtl'} >
      <body>
        <Provider locale={locale}>{children}</Provider>
      </body>
    </html>
  );
}